### PR TITLE
Handedness conversion + geometry unit scaling

### PR DESCRIPTION
**Pull request by bqqbarbhg**
Support converting between right-handed and left-handed coordinate spaces.

Also while modifying geometry add support for unit scaling via scaling geometry and translations.

### CODE REVIEW

**Comment by phil-pwg** [comment]
Is this ready to merge? I need to use the handedness conversion.

**Comment by phil-pwg** [comment]
FWIW,

I'm trying to convert from the right-handed `{right=UFBX_COORDINATE_AXIS_POSITIVE_X, up=UFBX_COORDINATE_AXIS_POSITIVE_Z, front=UFBX_COORDINATE_AXIS_NEGATIVE_Y}`

to left-handed `{right=UFBX_COORDINATE_AXIS_POSITIVE_Y, up=UFBX_COORDINATE_AXIS_POSITIVE_Z, front=UFBX_COORDINATE_AXIS_POSITIVE_X}`.

Using this feature branch I am not entering the ufbx_matrix_determinant(..) < 0.0f block that sets the handedness conversion mirror axis because `ufbx_matrix_determinant(&uc->axis_matrix)` evaluates to 1 in this case.  Is this an error? I tried editing it but still no luck on getting the full axis conversion result I am looking for with my animations.
```
static ufbxi_noinline void ufbxi_transform_to_axes(ufbxi_context *uc, ufbx_coordinate_axes dst_axes)
{
	if (!ufbx_coordinate_axes_valid(uc->scene.settings.axes)) return;
	if (!ufbxi_axis_matrix(&uc->axis_matrix, uc->scene.settings.axes, dst_axes)) return;

	if (ufbx_matrix_determinant(&uc->axis_matrix) < 0.0f) {
		if (uc->opts.handedness_conversion_axis != UFBX_MIRROR_AXIS_NONE) {
			ufbx_mirror_axis mirror_axis = uc->opts.handedness_conversion_axis;
			uc->mirror_axis = mirror_axis;
			uc->scene.metadata.mirror_axis = uc->mirror_axis;

			ufbxi_mirror_matrix_dst(&uc->axis_matrix, uc->mirror_axis);
			ufbxi_dev_assert(ufbx_matrix_determinant(&uc->axis_matrix) >= 0.0f);

			ufbxi_for_ptr_list(ufbx_node, p_node, uc->scene.nodes) {
				ufbx_node *node = *p_node;
				if (!node->is_root) {
					node->adjust_mirror_axis = mirror_axis;
				}
			}
		}
	}
```

**Comment by bqqbarbhg** [comment]
This branch is quite stable now and should be ready to merge soon, at least to `integration`. Merging to `master` will take a bit still, but in the meantime this branch and `integration` should be fine to use. The CI is extensive enough that any commit passing the tests is reasonably sturdy.

About the axis conversion, to me it looks like both the coordinate axes you described are left-handed (if I transcribed them correctly) and the transition between them should correspond to a 90 degree rotation about the Z axis, no mirroring needed. Cruddy mspaint I made for myself as they can be hard to visualize otherwise:

image

Notice that ufbx preserves the quirk of FBX that the _front_ axis is not specified as the _forward_ axis, which can be a bit confusing. There is a chance that ufbx incorrectly identifies the axes that are specified in the file. There are still some unknowns about how some of the axis combinations work in practice, I've only tested all up/front permutations exported by Blender, but their exporter may not match the actual "specification". It would be interesting if the file is actually left-handed as I have yet to see an actually left-handed FBX file in the wild.

Do you know what program was used to export the file in question so I could attempt to reproduce the issue? A test file (can just be a dummy with the same axes) would help with diagnosing the issue as well, but no worries if that's not something you can do.

**Comment by phil-pwg** [comment]
I appreciate the fast response.
If I understand correctly, I have been flipping the sign of the forward axis to specify the front axis.

I have re-written our model importer from OpenFBX to ufbx and can load all of our assets just fine again (static models, rigs, and animations).

My current issue is this:
My team exports our models & rigs from Blender with -X forward and Z up.
image
OpenFBX reports this as LeftHanded:
image

We now want to use iClone 8 to export single animations for use on rigs from Blender.
OpenFBX reports all of these as RightHanded with the same coordinate space from ufbx I specified above({right=UFBX_COORDINATE_AXIS_POSITIVE_X, up=UFBX_COORDINATE_AXIS_POSITIVE_Z, front=UFBX_COORDINATE_AXIS_NEGATIVE_Y}).
image

These iClone animations are then used on a rig exported directly from Blender that always has the proper coordinate space.
It doesn't seem to matter what fbx export option I select in iClone (e.g. Blender vs Cinema4d). It always reports as RightHanded with OpenFBX.

I'll see what I can do to get a test file tomorrow if that helps.

**Comment by phil-pwg** [comment]
Okay this is really strange.
I just tried using our original OpenFBX implementation and applied the iClone export using the Blender export settings to our rig exported from Blender with positive Z-up and negative X-forward.

Even though the iClone export reports the wrong coordinate space the animation is applied correctly and just works... I have no idea how. Maybe iClone is writing incorrect metadata?

**Comment by bqqbarbhg** [comment]
Strange for sure, the `CoordAxis` and `CoordAxisSign` is still a bit unsure to me, I've talked to some other unofficial FBX importer people who assumed it represented left/right handed coordinate system. When creating ufbx I assumed that `CoordAxis` is just the index of the axis `X=0, Y=1, Z=2` and `CoordAxisSign` would represent the sign of it. This seems to be how `UpAxis`/`UpAxisSign` and `FrontAxis`/`FrontAxisSign` behave already. I've heard that the other interpretation stems from FBX SDK where apparently coordinate systems are represented in some weird `Up/Handedness/Parity` definition (I've tried to avoid using the official SDK to keep ufbx as clean as possible).

At least Blender seems to export files with assuming the ufbx convention for axes: https://github.com/blender/blender-addons/blob/86bcdbd5c43ead8df5a46a353d6ec7428c152060/io_scene_fbx/export_fbx_bin.py#L3192-L3209

Also as the `RIGHT_HAND_AXES[]` implies all files exported from Blender seem to be intended to be right-handed. It is still possible that this interpretation is incorrect in Blender as well. Currently at least I have not seen enough non-Blender data to draw any final conclusions how the properties should be interpreted.

Thanks for the information! I'll try to see if I can get something out of iClone myself as well, since it at least does seem to be doing something interesting with `CoordAxis`, either different interpretation, actually left-handed file, or just a plain broken exporter.

**Comment by bqqbarbhg** [comment]
Took a look at the iClone trial version, but it was not able to export any FBX files (even though it was marketed to be capable of doing 30 FBX exports), so I unfortunately have no means of testing this currently.

**Comment by bqqbarbhg** [comment]
@phil-pwg You can reach me at gmail.com with the same name 'bqqbarbhg', probably best to copy it to avoid typos :D

**Comment by phil-pwg** [comment]
Got it. Looks like I had a bug in my rig importing that resulted in incorrect bind poses.
I switched to using the correct cluster matrix of `cluster.bind_to_world` and now it all loads properly on the main ufbx branch.
I appreciate your time and sorry for the confusion.

**Comment by bqqbarbhg** [comment]
@phil-pwg Yeah it is a bit odd. The coordinate space the file is in (`{right=UFBX_COORDINATE_AXIS_POSITIVE_X, up=UFBX_COORDINATE_AXIS_POSITIVE_Z, front=UFBX_COORDINATE_AXIS_NEGATIVE_Y}`) is extremely strange as it would be the first left-handed file I've ever seen. Especially if the exported file is supposed to be right-handed. This might indicate that there is still some edge cases in parsing coordinate axes in ufbx, or that the exporter does something wrong.

**Pull request merged**
