### PR TITLE
Add UFBX_REAL_IS_FLOAT to change ufbx_real to use float

### PR DESCRIPTION
**Pull request by kellygravelyn**
Just a simple change to enable me to build ufbx using floats instead of doubles for values. Default behavior is to use doubles still so this shouldn't be breaking to any existing code.

### CODE REVIEW

**Comment by bqqbarbhg** [comment]
Thanks for the PR, looks clean! I've been neglecting this for a good while now but there's two things that have kept me from doing this:

* Deciding whether it should detect `defined(UFBX_REAL_IS_FLOAT)` or that the value is not `0`. Currently the `ufbx.c` user defines are done via define-only, I think I checked that it was easier to control things like that in some build systems (?)
* The tests at least used to break with floats, so I'd like to make sure everything works before merging this

I can take a look at some point but if you're inclined in getting this merged fast feel free to add `"UFBX_REAL_IS_FLOAT=1"` to `feature_defines` in `misc/run_tests.py`:

https://github.com/ufbx/ufbx/blob/8475fc5f9f7d933a59d7f54dc55518dd2590797c/misc/run_tests.py#L941-L948

There is currently no library developer facing documentation so the situation is pretty rough, but locally compiling and running `ufbx.c` and `test/runner.c` with the `UFBX_REAL_IS_FLOAT=1` define.

But anyways thanks and no pressure to look into it yourself, I know the contributor experience isn't the greatest at the moment :D

**Comment by kellygravelyn** [comment]
Makes sense. I think `#if defined(UFBX_REAL_IS_FLOAT)` seems reasonable so I've switched it to that and then added it to the feature_defines in the run_tests.py. I saw there are some PR workflows that run tests so I figure those will cover running the tests for me?

**Comment by bqqbarbhg** [comment]
Yep that's the idea! I didn't realize I have to approve them for every commit, so I did that, though I'm a bit worried it'll fail in quaternion/Euler conversion tests as I remember :D

**Comment by bqqbarbhg** [comment]
Hmm looks like the `features` test only compiles the feature permutations, I see that I had write permissions for this so I'll try to get them running.

**Comment by bqqbarbhg** [comment]
Yea seems like there's some test failures now, most are probably fixable via using `double` internally in some places, will look into it a bit later.

**Comment by bqqbarbhg** [comment]
Got all the CI issues fixed, had an actual serious bug assuming `ufbx_real` is `double` internally as well. I don't run dataset tests with floats on CI as that'd take too much time but currently 278/283 files pass using floats. It's probably just some inaccuracy so hopefully I'll get those sorted out tomorrow and can merge this.

**Pull request merged**
